export const ruLocalization = {
  actions: 'Действия',
  and: 'и',
  cancel: 'Отмена',
  changeFilterMode: 'Изменить режим фильтра',
  changeSearchMode: 'Изменить режим поиска',
  clearFilter: 'Очистить',
  clearSearch: 'Очистить поиск',
  clearSort: 'Очистить сортировку',
  clickToCopy: 'Кликните, чтобы скопировать',
  columnActions: 'Действия с колонкой',
  copiedToClipboard: 'Скопировано в буфер обмена',
  dropToGroupBy: 'Перетащите сюда для группировки',
  edit: 'Редактировать',
  expand: 'Развернуть',
  expandAll: 'Развернуть всё',
  filterArrIncludes: 'Включает',
  filterArrIncludesAll: 'Включает все',
  filterArrIncludesSome: 'Включает некоторые',
  filterBetween: 'Между',
  filterBetweenAnd: 'Между',
  filterContains: 'Содержит',
  filterEmpty: 'Пустые',
  filterEndsWith: 'Заканчивается на',
  filterEquals: 'Равно',
  filterFalsy: 'Ложные значения',
  filterGreaterThan: 'Больше чем',
  filterGreaterThanOrEqualTo: 'Больше или равно',
  filterInNumberRange: 'В диапазоне',
  filterIncludesString: 'Содержит строку',
  filterLessThan: 'Меньше чем',
  filterLessThanOrEqualTo: 'Меньше или равно',
  filterMode: 'Режим фильтрации',
  filterNotEmpty: 'Не пустые',
  filterNotEquals: 'Не равно',
  filterStartsWith: 'Начинается с',
  filterTruthy: 'Истинные значения',
  filterByColumn: 'Фильтр по {column}',
  filteredByColumn: 'Отфильтровано по {column}',
  footerOfTotalRows: 'из {total} записей',
  groupByColumn: 'Группировать по {column}',
  hideAll: 'Скрыть все',
  hideColumn: 'Скрыть {column}',
  max: 'Макс.',
  min: 'Мин.',
  moveLeft: 'Влево',
  moveRight: 'Вправо',
  noRecordsToDisplay: 'Нет записей для отображения',
  noResultsFound: 'Ничего не найдено',
  of: 'из',
  or: 'или',
  pinToLeft: 'Закрепить слева',
  pinToRight: 'Закрепить справа',
  resetColumnSize: 'Сбросить размер',
  rowActions: 'Действия',
  rowNumber: '#',
  rowNumbers: 'Номер строки',
  rowsPerPage: 'Строк на странице',
  save: 'Сохранить',
  search: 'Поиск',
  select: 'Выбрать',
  selectedCountOfRowCountItemsSelected:
    '{selectedCount} из {rowCount} элементов выбрано',
  showAll: 'Показать все',
  showAllColumns: 'Показать все колонки',
  showHideColumns: 'Показать/скрыть столбцы',
  showHideFilters: 'Показать/скрыть фильтры',
  showHideSearch: 'Показать/скрыть поиск',
  showInFullScreen: 'На весь экран',
  sortByColumnAsc: 'Сортировать по возрастанию',
  sortByColumnDesc: 'Сортировать по убыванию',
  sortedByColumnAsc: 'Отсортировано по возрастанию',
  sortedByColumnDesc: 'Отсортировано по убыванию',
  thenBy: ', затем по ',
  toggleDensity: 'Изменить плотность',
  toggleFullScreen: 'Полноэкранный режим',
  toggleSelectAll: 'Выбрать все',
  toggleSelectRow: 'Выбрать строку',
  ungroupByColumn: 'Разгруппировать {column}',
  unpin: 'Открепить',
  unsorted: 'Без сортировки',
};
