import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import React from 'react';
import { CustomThemeProvider } from '@/providers/themeProvider';
import { SideBar } from '@/components/layout/sideBar';
import { Container } from '@mui/material';

const roboto = Roboto({
  subsets: ['latin', 'cyrillic'],
  weight: ['100', '300', '400', '500', '700', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <meta name='viewport' content='initial-scale=1, width=device-width' />
      </head>
      <body className={`${roboto.className} antialiased`}>
        <CustomThemeProvider>
          <Container
            maxWidth={'xl'}
            sx={{
              position: 'relative',
              padding: '0.75rem 0',
              height: '100dvh',
              boxSizing: 'border-box',
            }}
          >
            <SideBar />
            <div className={'h-full w-full pl-22'}>{children}</div>
          </Container>
        </CustomThemeProvider>
      </body>
    </html>
  );
}
